### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:52210 at createConnectionError (node:net:1634:14) at afterConnectMultiple (node:net:1664:40) { errno: -4078, code: 'ECONNREFUSED', syscall: 'connect', address: '127.0.0.1', port: 52210

### ISSUE THREAD

**Issue by miroshar-success** [OskarMast/next-tailwindcss-material#1]

**Comment by dancerking** [comment]
Hi, Oskar.
I have already met such issue before.
const response = await fetch('localhost:3000/api/user', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        name: 'John Doe',
        profilePicture: '<https://example.com/profile.jpg',>
      }),
    });
    You can give full url of fetch request.
But this method is not recommended for Next.js
You should use fetch method on client component.
You can access to DB on Server Component.
Happy Lucky!

**Comment by miroshar-success** [comment]
Oh. Good.
Perfect resolution.
Thanks

**Comment by dancerking** [comment]
Good
